title: Fabian Salvador Diaz Navarro
author: FabianDiazN
email: l18101140@tecnm.mx
description:
Tecnologías de la Información y la Comunicación es un término extensivo para la tecnología de la información que enfatiza el papel de las comunicaciones unificadas, 
la integración de las telecomunicaciones

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
